
services:
  ollama-sever:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    image: ollama-server
    ports:
      - "11434:11434"
    networt:
      - my-net:
    entrypoint: ["sh", "/app/pull-model.sh"]
    container_name: ollama-server
    environment:
      OLLAMA_MODEL: "llama3.2:3b"


networt:
  my-net:
    driver: bridge
    
