
services:
  ollama-sever:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    image: ollama-server
    ports:
      - "11434:11434"
    networt:
      - my-net:
    command: [/pull-model.sh]
    container_name: ollama-server


networt:
  my-net:
    driver: bridge
    
